### ISSUE TITLE
Removing mod causes world to corrupt.

### ISSUE THREAD

**Issue by kiwiandoesthings** [Andrew6rant/Auto-Slabs#42]
I was playing (on a server) with this mod. The hardware isn't that great and the mod was kinda laggy so I removed it. Upon relaunching, lots of different blocks were replaced with other random blocks. Tall grass became double dark prismarine slabs, bamboo became shulker boxes etc. This really needs to be reworked, if possible, especially because I would still like to remove this mod from my server without having to reset the world.

**Comment by Andrew6rant** [comment]
I've taken precautions to prevent AutoSlabs from doing this.

Are you sure you removed the mod from both the server and clients? These types of blockstate mismatches can visually appear if a client has the mod, but the server doesn't.

I'd love to see some server and client log files, if you still have them

**Comment by kiwiandoesthings** [comment]
It’s been a while and I don’t have that server anymore. I’m pretty sure the mod was removed from the client too (I was playing with a few of my friends) but I can’t be sure.

**Comment by Andrew6rant** [comment]
Yeah it's understandable to not keep logs for several months (I haven't been good about checking issues on this repo at all). I'll close this for now, and re-open it if I get another report of world corruption
