### ISSUE TITLE
vertical glass slab texture

### ISSUE THREAD

**Issue by DadoIrie** [Andrew6rant/Auto-Slabs#5]
that's what I meant earlier in a another issue - btw those are from [Mo Glass](https://www.curseforge.com/minecraft/mc-mods/mo-glass)

![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/0287bcef-3aa0-4fd0-941f-28abe8744f96)
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/43fb1a23-9366-4353-9cd7-786bc32c2509)
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/ff0d6bb5-c5ee-4dee-a438-8260353791be)
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/2e9dd6a2-3158-43ca-bbc9-cc3a4cff4e69)
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/be0c48c6-94aa-43a0-983d-2349987043cd)
![image](https://github.com/Andrew6rant/Auto-Slabs/assets/61109153/7e767ac6-7bb9-4679-8711-9c7949003c28)

**Comment by Andrew6rant** [comment]
This isn't an AutoSlabs issue, Mo' Glass handles their models in a weird way. You can fix it with a resource pack.

I might look into adding built-in support though.

**Comment by DadoIrie** [comment]
no idea how the resourcepack should be looking - I'm just starting with a GUI resource pack - not touching blocks (for now ... and if then just adding some tweaks like shiny animation with mcmeta when a amethyst cluster is ready ... still learning)

**Comment by Andrew6rant** [comment]
![AutoSlabs Mo' Glass texture compat](https://github.com/Andrew6rant/Auto-Slabs/assets/57331134/1cbe168a-4d64-4c5f-8492-8f63b36773d9)

Here is a commit that adds texture and model support to Mo Glass' glass slab: https://github.com/Andrew6rant/Auto-Slabs/commit/b33cd4be9353e8f10405ac18fa79894ebb8cc778. You can see how I set up the model JSONs. I'm not going to add support for the rest of Mo Glass' blocks (not now, at least), so if you want them in the mod, feel free to make a PR.

**Comment by DadoIrie** [comment]
thanks - will take a look

**Comment by Andrew6rant** [comment]
Related issue - https://github.com/Andrew6rant/Auto-Slabs/issues/12

**Comment by DadoIrie** [comment]
sorry for that late PR #17 - tested and works ... yeah I did notice #12 and notice also sometimes randomly switching place from left to right or vice versa(and even from vertical to horizontal & vice versa, but this one is very rare) when placing a vertical slab - which ain't either a huge deal as it doesn't happen that often (but that's another issue not related with this one as it doesn't affect only glass slabs)

EDIT: feel free closing this issue once #17 is accepted
