### ISSUE TITLE
Sneaking While Mining Single Slabs Causes Duplication

### ISSUE THREAD

**Issue by Superkat32** [Andrew6rant/Auto-Slabs#8]
If you sneak while mining a single slab, it drops 2 slabs instead of one. Seems to happen for all types of slabs(wooden, stone, etc.), but I haven't tested with modded slabs.

Minecraft Version: 1.20.1
AutoSlabs Version: 1.0.1

Video:

https://github.com/Andrew6rant/Auto-Slabs/assets/89557012/2d8c4484-e679-4243-81de-a8297c0a4a92

Other mods present in the video were Mod Menu and Fabric API.

Currently working on a PR to fix if you haven't fixed it locally already.

**Comment by DadoIrie** [comment]
confirming that this happens also with modded slabs

**Comment by DadoIrie** [comment]
What do you mean with "more duplication elsewhere" with that commit which changes the sneak? ... does this also mean no mining vertical slabs when sneaking?

**Comment by Superkat32** [comment]
Whenever I tried removing that if statement, it fixed the duplication when sneaking, but then caused duplication for mining a single slab on a 2 slab block when not sneaking. That's what I've kept the if statement. Should the pull request get merged, you would still be good to mine vertical slabs, sneaking or not.

**Comment by Andrew6rant** [comment]
Yeah that sneaking check was to try and fix the dupe bug (meant for KleeSlabs functionality). Didn't realize it caused another dupe, haha
